version: "3.8"
services:
  mysql:
    image: "mysql/mysql-server:8.0.32"
    environment:
      - MYSQL_DB=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - TZ=${MYSQL_TZ}
    volumes:
      - "mysql:/var/lib/mysql"
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      retries: 3
      timeout: 5s
  database:
    image: database
    env_file: ./packages/database/.env
    build:
      context: .
      dockerfile: ./packages/database/Dockerfile
    tty: true
    volumes:
      - ./packages/database:/app/packages/database:cached
      - root_node_modules:/app/node_modules
      - database_node_modules:/app/packages/database/node_modules
    ports:
      - "5555:5555"
    depends_on:
      - mysql
    networks:
      - anidge
  user:
    image: user
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
    tty: true
    volumes:
      - ./apps/user:/app/apps/user:cached
      - root_node_modules:/app/node_modules
      - apps_node_modules:/app/apps/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - database
    networks:
      - anidge
  provider:
    image: provider
    build:
      context: .
      dockerfile: ./apps/provider/Dockerfile
    tty: true
    volumes:
      - ./apps/provider:/app/apps/provider:cached
      - root_node_modules:/app/node_modules
      - apps_node_modules:/app/apps/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - mysql
      - database
    networks:
      - anidge
  admin:
    image: admin
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
    tty: true
    volumes:
      - ./apps/admin:/app/apps/admin:cached
      - root_node_modules:/app/node_modules
      - apps_node_modules:/app/apps/node_modules
    ports:
      - "3002:3002"
    depends_on:
      - mysql
      - database
    networks:
      - anidge
networks:
  anidge:
    driver: bridge
volumes:
  mysql:
  root_node_modules:
  apps_node_modules:
  database_node_modules:
